apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
#spec for deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    #spec for pod
    spec:
      containers:
        - name: hello-nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "100Mi"
              cpu: "250m"
          #define the volume mount
          volumeMounts:
            #define the path where the volume will be mounted inside container
            - mountPath: /etc/nginx/conf.d
              #tells if is readOnly
              readOnly: true
              #tells the mount which is the volume to mount
              name: nginx-conf

      #creates a volume
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf


